name: instagram_clone
description: instagram offline-first clone
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  bloc: ^9.0.0
  env:
    path: packages/env
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.3
  google_sign_in: ^6.2.2
  intl: ^0.19.0
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared  
dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
