name: instagram_clone
description: instagram offline-first clone
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  animations: ^2.0.11
  auth_client:
    path: packages/auth_client/auth_client
  bloc: ^8.1.3
  database_client:
    path: packages/database_client
  env:
    path: packages/env
  equatable: ^2.0.7
  firebase_core: ^3.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  forms:
    path: packages/forms
  get_it: ^8.0.3
  go_router: ^12.1.3
  google_sign_in: ^6.2.2
  instagram_related_ui:
    path: packages/instagram_related_ui
  intl: ^0.19.0
  pausable_timer: ^3.1.0+3
  posts_repository:
    path: packages/posts_repository
  powersync_repository:
    path: packages/powersync_repository
  shared:
    path: packages/shared
  sliver_tools: ^0.2.12
  supabase_auth_client:
    path: packages/auth_client/supabase_auth_client
  token_storage:
    path: packages/auth_client/token_storage
  ui:
    path: packages/ui
  user_repository:
    path: packages/user_repository
dev_dependencies:
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
