// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaTkEZgwTFfqo6hvC_MB1Ge8ZfdKugorY',
    appId: '1:327497887294:web:9631881421434185c1ab6f',
    messagingSenderId: '327497887294',
    projectId: 'instagram-clone-bd90a',
    authDomain: 'instagram-clone-bd90a.firebaseapp.com',
    storageBucket: 'instagram-clone-bd90a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlQ4LpmlMYsOGPJ618I6Z4yGeZzd8LOIQ',
    appId: '1:327497887294:android:45f29bff8dd612c3c1ab6f',
    messagingSenderId: '327497887294',
    projectId: 'instagram-clone-bd90a',
    storageBucket: 'instagram-clone-bd90a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2dJKl6GXt8R4e_FM7EOdC1lxDyEBlCuE',
    appId: '1:327497887294:ios:a70e3acc633d3a85c1ab6f',
    messagingSenderId: '327497887294',
    projectId: 'instagram-clone-bd90a',
    storageBucket: 'instagram-clone-bd90a.firebasestorage.app',
    iosClientId: '327497887294-8hn6ppikc0aklovncmm1ebj9nqe5kteu.apps.googleusercontent.com',
    iosBundleId: 'com.amirpooyani.org.flutterInstagramClone',
  );

}