name: env
description: A Repository for managing environment vareables
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  envied: ^1.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.4.9
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
