name: powersync_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  env:
    path: ../env
  flutter:
    sdk: flutter
  path: ">=1.8.3 <=1.9.1"
  path_provider: ^2.1.4
  powersync: ^1.4.2
  shared:
    path: ../shared
  supabase_flutter: ^2.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
